-- AlterTable
ALTER TABLE "comments" ADD COLUMN     "updated_at" TIMESTAMPTZ(2) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "post_liked" ADD COLUMN     "created_at" TIMESTAMPTZ(2) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMPTZ(2) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "posts" ADD COLUMN     "updated_at" TIMESTAMPTZ(2) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "updated_at" TIMESTAMPTZ(2) NOT NULL DEFAULT CURRENT_TIMESTAMP;
