name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Docker Login
        run: |
          echo "Verifying Docker login status..."
          docker info
          echo "Current Docker images:"
          docker images

      - name: Build Docker images
        run: |
          echo "Building Docker images..."
          docker-compose build --no-cache
          echo "Listing built images:"
          docker images
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: Push Docker images
        run: |
          echo "Attempting to push images..."
          docker-compose push
          echo "Push completed"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
